export interface ICompetitionDataItem {
  id: number
  title: string
  country: string
  countryCode: string
}

export const competitionData: ICompetitionDataItem[] = [
  {
    id: 2006,
    title: "WC Qualification CAF",
    country: "Africa",
    countryCode: "AF",
  },
  {
    id: 2023,
    title: "Primera B Nacional",
    country: "Argentina",
    countryCode: "AR",
  },
  {
    id: 2024,
    title: "Liga Profesional",
    country: "Argentina",
    countryCode: "AR",
  },
  {
    id: 2025,
    title: "Supercopa Argentina",
    country: "Argentina",
    countryCode: "AR",
  },
  {
    id: 2149,
    title: "Copa Liga Profesional",
    country: "Argentina",
    countryCode: "AR",
  },
  {
    id: 2147,
    title: "WC Qualification AFC",
    country: "Asia",
    countryCode: "AS",
  },
  {
    id: 2008,
    title: "A League",
    country: "Australia",
    countryCode: "AU",
  },
  {
    id: 2026,
    title: "FFA Cup",
    country: "Australia",
    countryCode: "AU",
  },
  {
    id: 2020,
    title: "Erste Liga",
    country: "Austria",
    countryCode: "AU",
  },
  {
    id: 2012,
    title: "Bundesliga",
    country: "Austria",
    countryCode: "AU",
  },
  {
    id: 2022,
    title: "Playoffs 1/2",
    country: "Austria",
    countryCode: "AU",
  },
  {
    id: 2027,
    title: "ÖFB Cup",
    country: "Austria",
    countryCode: "AU",
  },
  {
    id: 2028,
    title: "Coupe de Belgique",
    country: "Belgium",
    countryCode: "BE",
  },
  {
    id: 2033,
    title: "Division 1B",
    country: "Belgium",
    countryCode: "BE",
  },
  {
    id: 2009,
    title: "Jupiler Pro League",
    country: "Belgium",
    countryCode: "BE",
  },
  {
    id: 2010,
    title: "Supercoupe de Belgique",
    country: "Belgium",
    countryCode: "BE",
  },
  {
    id: 2032,
    title: "Playoffs II",
    country: "Belgium",
    countryCode: "BE",
  },
  {
    id: 2034,
    title: "LFPB",
    country: "Bolivia",
    countryCode: "BO",
  },
  {
    id: 2035,
    title: "Premier Liga",
    country: "Bosnia and Herzegovina",
    countryCode: "BI",
  },
  {
    id: 2037,
    title: "Copa do Brasil",
    country: "Brazil",
    countryCode: "BR",
  },
  {
    id: 2038,
    title: "Série D",
    country: "Brazil",
    countryCode: "BR",
  },
  {
    id: 2036,
    title: "Série C",
    country: "Brazil",
    countryCode: "BR",
  },
  {
    id: 2029,
    title: "Campeonato Brasileiro Série B",
    country: "Brazil",
    countryCode: "BR",
  },
  {
    id: 2013,
    title: "Campeonato Brasileiro Série A",
    country: "Brazil",
    countryCode: "BR",
  },
  {
    id: 2039,
    title: "Kupa na Bulgarija",
    country: "Bulgaria",
    countryCode: "BG",
  },
  {
    id: 2040,
    title: "A PFG",
    country: "Bulgaria",
    countryCode: "BG",
  },
  {
    id: 2041,
    title: "Canadian Championship",
    country: "Canada",
    countryCode: "CA",
  },
  {
    id: 2042,
    title: "Playoffs 1/2",
    country: "Chile",
    countryCode: "CH",
  },
  {
    id: 2043,
    title: "Supercopa de Chile",
    country: "Chile",
    countryCode: "CH",
  },
  {
    id: 2048,
    title: "Primera División",
    country: "Chile",
    countryCode: "CH",
  },
  {
    id: 2044,
    title: "Chinese Super League",
    country: "China PR",
    countryCode: "CH",
  },
  {
    id: 2045,
    title: "Liga Postobón",
    country: "Colombia",
    countryCode: "CO",
  },
  {
    id: 2046,
    title: "Superliga de Colombia",
    country: "Colombia",
    countryCode: "CO",
  },
  {
    id: 2047,
    title: "Prva Liga",
    country: "Croatia",
    countryCode: "HR",
  },
  {
    id: 2049,
    title: "Synot Liga",
    country: "Czech Republic",
    countryCode: "CZ",
  },
  {
    id: 2051,
    title: "DBU Pokalen",
    country: "Denmark",
    countryCode: "DK",
  },
  {
    id: 2050,
    title: "Superliga",
    country: "Denmark",
    countryCode: "DK",
  },
  {
    id: 2141,
    title: "Play Offs 1/2",
    country: "Denmark",
    countryCode: "DK",
  },
  {
    id: 2052,
    title: "Copa Pilsener Serie A",
    country: "Ecuador",
    countryCode: "EC",
  },
  {
    id: 2139,
    title: "Football League Cup",
    country: "England",
    countryCode: "GB-ENG",
  },
  {
    id: 2056,
    title: "FA Community Shield",
    country: "England",
    countryCode: "GB-ENG",
  },
  {
    id: 2055,
    title: "FA Cup",
    country: "England",
    countryCode: "GB-ENG",
  },
  {
    id: 2053,
    title: "National League",
    country: "England",
    countryCode: "GB-ENG",
  },
  {
    id: 2054,
    title: "League Two",
    country: "England",
    countryCode: "GB-ENG",
  },
  {
    id: 2030,
    title: "League One",
    country: "England",
    countryCode: "GB-ENG",
  },
  {
    id: 2016,
    title: "Championship",
    country: "England",
    countryCode: "GB-ENG",
  },
  {
    id: 2021,
    title: "Premier League",
    country: "England",
    countryCode: "GB-ENG",
  },
  {
    id: 2057,
    title: "Meistriliiga",
    country: "Estonia",
    countryCode: "ES",
  },
  {
    id: 2146,
    title: "UEFA Europa League",
    country: "Europe",
    countryCode: "EU",
  },
  {
    id: 2001,
    title: "UEFA Champions League",
    country: "Europe",
    countryCode: "EU",
  },
  {
    id: 2018,
    title: "European Championship",
    country: "Europe",
    countryCode: "EU",
  },
  {
    id: 2154,
    title: "UEFA Conference League",
    country: "Europe",
    countryCode: "EU",
  },
  {
    id: 2007,
    title: "WC Qualification UEFA",
    country: "Europe",
    countryCode: "EU",
  },
  {
    id: 2058,
    title: "UEFA Women's EURO",
    country: "Europe",
    countryCode: "EU",
  },
  {
    id: 2059,
    title: "Suomen Cup",
    country: "Finland",
    countryCode: "FI",
  },
  {
    id: 2031,
    title: "Veikkausliiga",
    country: "Finland",
    countryCode: "FI",
  },
  {
    id: 2135,
    title: "Coupe de la Ligue",
    country: "France",
    countryCode: "FR",
  },
  {
    id: 2142,
    title: "Ligue 2",
    country: "France",
    countryCode: "FR",
  },
  {
    id: 2015,
    title: "Ligue 1",
    country: "France",
    countryCode: "FR",
  },
  {
    id: 2136,
    title: "Trophée des Champions",
    country: "France",
    countryCode: "FR",
  },
  {
    id: 2143,
    title: "Playoffs 1/2",
    country: "France",
    countryCode: "FR",
  },
  {
    id: 2144,
    title: "Playoffs 2/3",
    country: "France",
    countryCode: "FR",
  },
  {
    id: 2138,
    title: "Coupe de France",
    country: "France",
    countryCode: "FR",
  },
  {
    id: 2011,
    title: "DFB-Pokal",
    country: "Germany",
    countryCode: "DE",
  },
  {
    id: 2129,
    title: "Regionalliga",
    country: "Germany",
    countryCode: "DE",
  },
  {
    id: 2140,
    title: "3. Liga",
    country: "Germany",
    countryCode: "DE",
  },
  {
    id: 2004,
    title: "2. Bundesliga",
    country: "Germany",
    countryCode: "DE",
  },
  {
    id: 2002,
    title: "Bundesliga",
    country: "Germany",
    countryCode: "DE",
  },
  {
    id: 2133,
    title: "Frauen Bundesliga",
    country: "Germany",
    countryCode: "DE",
  },
  {
    id: 2134,
    title: "DFL Super Cup",
    country: "Germany",
    countryCode: "DE",
  },
  {
    id: 2131,
    title: "Greek Cup",
    country: "Greece",
    countryCode: "GR",
  },
  {
    id: 2132,
    title: "Super League",
    country: "Greece",
    countryCode: "GR",
  },
  {
    id: 2150,
    title: "Souper Kap Ellados",
    country: "Greece",
    countryCode: "GR",
  },
  {
    id: 2130,
    title: "Magyar Kupa",
    country: "Hungary",
    countryCode: "HU",
  },
  {
    id: 2128,
    title: "NB I",
    country: "Hungary",
    countryCode: "HU",
  },
  {
    id: 2127,
    title: "Úrvalsdeild",
    country: "Iceland",
    countryCode: "IS",
  },
  {
    id: 2126,
    title: "I-League",
    country: "India",
    countryCode: "IN",
  },
  {
    id: 2125,
    title: "Ligat ha'Al",
    country: "Israel",
    countryCode: "IS",
  },
  {
    id: 2124,
    title: "Supercoppa",
    country: "Italy",
    countryCode: "IT",
  },
  {
    id: 2122,
    title: "Coppa Italia",
    country: "Italy",
    countryCode: "IT",
  },
  {
    id: 2123,
    title: "Serie C",
    country: "Italy",
    countryCode: "IT",
  },
  {
    id: 2121,
    title: "Serie B",
    country: "Italy",
    countryCode: "IT",
  },
  {
    id: 2019,
    title: "Serie A",
    country: "Italy",
    countryCode: "IT",
  },
  {
    id: 2118,
    title: "J.League Cup",
    country: "Japan",
    countryCode: "JP",
  },
  {
    id: 2117,
    title: "J. League Division 2",
    country: "Japan",
    countryCode: "JP",
  },
  {
    id: 2119,
    title: "J. League",
    country: "Japan",
    countryCode: "JP",
  },
  {
    id: 2120,
    title: "Super Cup",
    country: "Japan",
    countryCode: "JP",
  },
  {
    id: 2116,
    title: "Virslīga",
    country: "Latvia",
    countryCode: "LV",
  },
  {
    id: 2115,
    title: "A Lyga",
    country: "Lithuania",
    countryCode: "LT",
  },
  {
    id: 2114,
    title: "Premier League",
    country: "Malta",
    countryCode: "ML",
  },
  {
    id: 2112,
    title: "SuperCopa MX",
    country: "Mexico",
    countryCode: "ME",
  },
  {
    id: 2111,
    title: "Copa MX",
    country: "Mexico",
    countryCode: "ME",
  },
  {
    id: 2113,
    title: "Liga MX",
    country: "Mexico",
    countryCode: "ME",
  },
  {
    id: 2109,
    title: "KNVB Beker",
    country: "Netherlands",
    countryCode: "NL",
  },
  {
    id: 2005,
    title: "Eerste Divisie",
    country: "Netherlands",
    countryCode: "NL",
  },
  {
    id: 2003,
    title: "Eredivisie",
    country: "Netherlands",
    countryCode: "NL",
  },
  {
    id: 2110,
    title: "Johan Cruijff Schaal",
    country: "Netherlands",
    countryCode: "NL",
  },
  {
    id: 2108,
    title: "League Cup",
    country: "Northern Ireland",
    countryCode: "NI",
  },
  {
    id: 2107,
    title: "Premiership",
    country: "Northern Ireland",
    countryCode: "NI",
  },
  {
    id: 2106,
    title: "Tippeligaen",
    country: "Norway",
    countryCode: "NO",
  },
  {
    id: 2105,
    title: "1. divisjon",
    country: "Norway",
    countryCode: "NO",
  },
  {
    id: 2104,
    title: "Playoffs 1/2",
    country: "Norway",
    countryCode: "NO",
  },
  {
    id: 2103,
    title: "WC Qualification OFC",
    country: "Oceania",
    countryCode: "FM",
  },
  {
    id: 2102,
    title: "Liga Panameña de Fútbol",
    country: "Panama",
    countryCode: "PA",
  },
  {
    id: 2101,
    title: "Primera División",
    country: "Peru",
    countryCode: "PE",
  },
  {
    id: 2099,
    title: "Superpuchar Polski",
    country: "Poland",
    countryCode: "PL",
  },
  {
    id: 2100,
    title: "Puchar Polski",
    country: "Poland",
    countryCode: "PL",
  },
  {
    id: 2098,
    title: "Taça de Portugal",
    country: "Portugal",
    countryCode: "PR",
  },
  {
    id: 2096,
    title: "Liga2 Cabovisão",
    country: "Portugal",
    countryCode: "PR",
  },
  {
    id: 2017,
    title: "Primeira Liga",
    country: "Portugal",
    countryCode: "PR",
  },
  {
    id: 2097,
    title: "Supertaça Cândido de Oliveira",
    country: "Portugal",
    countryCode: "PR",
  },
  {
    id: 2095,
    title: "Premier Division",
    country: "Republic of Ireland",
    countryCode: "IR",
  },
  {
    id: 2092,
    title: "Liga II",
    country: "Romania",
    countryCode: "RO",
  },
  {
    id: 2094,
    title: "Liga I",
    country: "Romania",
    countryCode: "RO",
  },
  {
    id: 2093,
    title: "Supercupa României",
    country: "Romania",
    countryCode: "RO",
  },
  {
    id: 2089,
    title: "Russian Cup",
    country: "Russia",
    countryCode: "RU",
  },
  {
    id: 2088,
    title: "FNL",
    country: "Russia",
    countryCode: "RU",
  },
  {
    id: 2137,
    title: "RFPL",
    country: "Russia",
    countryCode: "RU",
  },
  {
    id: 2090,
    title: "Playoffs 1/2",
    country: "Russia",
    countryCode: "RU",
  },
  {
    id: 2091,
    title: "Russian Super Cup",
    country: "Russia",
    countryCode: "RU",
  },
  {
    id: 2087,
    title: "Scottish Cup",
    country: "Scotland",
    countryCode: "SC",
  },
  {
    id: 2085,
    title: "Championship",
    country: "Scotland",
    countryCode: "SC",
  },
  {
    id: 2084,
    title: "Premier League",
    country: "Scotland",
    countryCode: "SC",
  },
  {
    id: 2086,
    title: "Playoffs 2/3",
    country: "Scotland",
    countryCode: "SC",
  },
  {
    id: 2083,
    title: "ABSA Premiership",
    country: "South Africa",
    countryCode: "RS",
  },
  {
    id: 2152,
    title: "Copa Libertadores",
    country: "South America",
    countryCode: "SA",
  },
  {
    id: 2080,
    title: "Copa America",
    country: "South America",
    countryCode: "SA",
  },
  {
    id: 2081,
    title: "Copa Sudamericana",
    country: "South America",
    countryCode: "SA",
  },
  {
    id: 2082,
    title: "WC Qualification CONMEBOL",
    country: "South America",
    countryCode: "SA",
  },
  {
    id: 2079,
    title: "Copa del Rey",
    country: "Spain",
    countryCode: "ES",
  },
  {
    id: 2077,
    title: "Segunda División",
    country: "Spain",
    countryCode: "ES",
  },
  {
    id: 2014,
    title: "Primera Division",
    country: "Spain",
    countryCode: "ES",
  },
  {
    id: 2078,
    title: "Supercopa de España",
    country: "Spain",
    countryCode: "ES",
  },
  {
    id: 2074,
    title: "Superettan",
    country: "Sweden",
    countryCode: "SE",
  },
  {
    id: 2073,
    title: "Allsvenskan",
    country: "Sweden",
    countryCode: "SE",
  },
  {
    id: 2075,
    title: "Playoffs 2/3",
    country: "Sweden",
    countryCode: "SE",
  },
  {
    id: 2151,
    title: "Svenska Supercupen",
    country: "Sweden",
    countryCode: "SE",
  },
  {
    id: 2076,
    title: "Playoffs 1/2",
    country: "Sweden",
    countryCode: "SE",
  },
  {
    id: 2071,
    title: "Schweizer Pokal",
    country: "Switzerland",
    countryCode: "CH",
  },
  {
    id: 2072,
    title: "Super League",
    country: "Switzerland",
    countryCode: "CH",
  },
  {
    id: 2068,
    title: "1. Lig",
    country: "Turkey",
    countryCode: "TR",
  },
  {
    id: 2070,
    title: "Süper Lig",
    country: "Turkey",
    countryCode: "TR",
  },
  {
    id: 2069,
    title: "TFF Süper Kupa",
    country: "Turkey",
    countryCode: "TR",
  },
  {
    id: 2065,
    title: "Kubok Ukrainy",
    country: "Ukraine",
    countryCode: "UA",
  },
  {
    id: 2064,
    title: "Premier Liha",
    country: "Ukraine",
    countryCode: "UA",
  },
  {
    id: 2067,
    title: "Superkubok Ukrainy",
    country: "Ukraine",
    countryCode: "UA",
  },
  {
    id: 2066,
    title: "Playoffs 1/2",
    country: "Ukraine",
    countryCode: "UA",
  },
  {
    id: 2145,
    title: "MLS",
    country: "United States",
    countryCode: "US",
  },
  {
    id: 2063,
    title: "Primera División",
    country: "Uruguay",
    countryCode: "UY",
  },
  {
    id: 2148,
    title: "Supercopa Uruguaya",
    country: "Uruguay",
    countryCode: "UY",
  },
  {
    id: 2062,
    title: "Primera División",
    country: "Venezuela",
    countryCode: "VE",
  },
  {
    id: 2061,
    title: "V-League",
    country: "Vietnam",
    countryCode: "VN",
  },
  {
    id: 2060,
    title: "Welsh Premier League",
    country: "Wales",
    countryCode: "GB-WLS",
  },
  {
    id: 2000,
    title: "FIFA World Cup",
    country: "World",
    countryCode: "EU",
  },
  {
    id: 2155,
    title: "WC Qualification CONCACAF",
    country: "World",
    countryCode: "EU",
  },
  {
    id: 2153,
    title: "Summer Olympics",
    country: "World",
    countryCode: "EU",
  },
]
