export interface ITeamDataItem {
  id: number
  name: string
  country: string
  crest: string
}

export const teamData: ITeamDataItem[] = [
  {
    id: 57,
    name: "Arsenal FC",
    country: "England",
    crest: "https://crests.football-data.org/57.png",
  },
  {
    id: 58,
    name: "Aston Villa FC",
    country: "England",
    crest: "https://crests.football-data.org/58.svg",
  },
  {
    id: 59,
    name: "Blackburn Rovers FC",
    country: "England",
    crest: "https://crests.football-data.org/59.png",
  },
  {
    id: 60,
    name: "Bolton Wanderers FC",
    country: "England",
    crest: "https://crests.football-data.org/60.svg",
  },
  {
    id: 61,
    name: "Chelsea FC",
    country: "England",
    crest: "https://crests.football-data.org/61.png",
  },
  {
    id: 62,
    name: "Everton FC",
    country: "England",
    crest: "https://crests.football-data.org/62.png",
  },
  {
    id: 63,
    name: "Fulham FC",
    country: "England",
    crest: "https://crests.football-data.org/63.svg",
  },
  {
    id: 64,
    name: "Liverpool FC",
    country: "England",
    crest: "https://crests.football-data.org/64.png",
  },
  {
    id: 65,
    name: "Manchester City FC",
    country: "England",
    crest: "https://crests.football-data.org/65.png",
  },
  {
    id: 66,
    name: "Manchester United FC",
    country: "England",
    crest: "https://crests.football-data.org/66.png",
  },
  {
    id: 67,
    name: "Newcastle United FC",
    country: "England",
    crest: "https://crests.football-data.org/67.png",
  },
  {
    id: 68,
    name: "Norwich City FC",
    country: "England",
    crest: "https://upload.wikimedia.org/wikipedia/en/8/8c/Norwich_City.svg",
  },
  {
    id: 69,
    name: "Queens Park Rangers FC",
    country: "England",
    crest: "https://crests.football-data.org/69.png",
  },
  {
    id: 70,
    name: "Stoke City FC",
    country: "England",
    crest: "https://crests.football-data.org/70.png",
  },
  {
    id: 71,
    name: "Sunderland AFC",
    country: "England",
    crest: "https://crests.football-data.org/71.png",
  },
  {
    id: 73,
    name: "Tottenham Hotspur FC",
    country: "England",
    crest: "https://crests.football-data.org/73.svg",
  },
  {
    id: 74,
    name: "West Bromwich Albion FC",
    country: "England",
    crest: "https://crests.football-data.org/74.png",
  },
  {
    id: 75,
    name: "Wigan Athletic FC",
    country: "England",
    crest: "https://crests.football-data.org/75.svg",
  },
  {
    id: 76,
    name: "Wolverhampton Wanderers FC",
    country: "England",
    crest: "https://crests.football-data.org/76.svg",
  },
  {
    id: 322,
    name: "Hull City AFC",
    country: "England",
    crest: "https://crests.football-data.org/322.png",
  },
  {
    id: 328,
    name: "Burnley FC",
    country: "England",
    crest: "https://crests.football-data.org/328.png",
  },
  {
    id: 332,
    name: "Birmingham City FC",
    country: "England",
    crest: "https://crests.football-data.org/332.png",
  },
  {
    id: 336,
    name: "Blackpool FC",
    country: "England",
    crest: "https://crests.football-data.org/336.png",
  },
  {
    id: 338,
    name: "Leicester City FC",
    country: "England",
    crest: "https://crests.football-data.org/338.png",
  },
  {
    id: 340,
    name: "Southampton FC",
    country: "England",
    crest: "https://crests.football-data.org/340.png",
  },
  {
    id: 341,
    name: "Leeds United FC",
    country: "England",
    crest: "https://crests.football-data.org/341.png",
  },
  {
    id: 342,
    name: "Derby County FC",
    country: "England",
    crest: "https://crests.football-data.org/342.svg",
  },
  {
    id: 343,
    name: "Middlesbrough FC",
    country: "England",
    crest: "https://crests.football-data.org/343.png",
  },
  {
    id: 345,
    name: "Sheffield Wednesday FC",
    country: "England",
    crest: "https://crests.football-data.org/345.png",
  },
  {
    id: 346,
    name: "Watford FC",
    country: "England",
    crest: "https://crests.football-data.org/346.svg",
  },
  {
    id: 348,
    name: "Charlton Athletic FC",
    country: "England",
    crest: "https://crests.football-data.org/348.png",
  },
  {
    id: 349,
    name: "Ipswich Town FC",
    country: "England",
    crest: "https://crests.football-data.org/349.svg",
  },
  {
    id: 351,
    name: "Nottingham Forest FC",
    country: "England",
    crest: "https://crests.football-data.org/351.svg",
  },
  {
    id: 354,
    name: "Crystal Palace FC",
    country: "England",
    crest: "https://crests.football-data.org/354.png",
  },
  {
    id: 355,
    name: "Reading FC",
    country: "England",
    crest: "https://crests.football-data.org/355.svg",
  },
  {
    id: 356,
    name: "Sheffield United FC",
    country: "England",
    crest: "https://crests.football-data.org/356.svg",
  },
  {
    id: 357,
    name: "Barnsley FC",
    country: "England",
    crest: "https://crests.football-data.org/357.png",
  },
  {
    id: 384,
    name: "Millwall FC",
    country: "England",
    crest: "https://crests.football-data.org/384.png",
  },
  {
    id: 385,
    name: "Rotherham United FC",
    country: "England",
    crest: "https://crests.football-data.org/385.png",
  },
  {
    id: 387,
    name: "Bristol City FC",
    country: "England",
    crest: "https://crests.football-data.org/387.svg",
  },
  {
    id: 389,
    name: "Luton Town FC",
    country: "England",
    crest: "https://crests.football-data.org/389.png",
  },
  {
    id: 394,
    name: "Huddersfield Town AFC",
    country: "England",
    crest: "https://crests.football-data.org/394.png",
  },
  {
    id: 397,
    name: "Brighton & Hove Albion FC",
    country: "England",
    crest: "https://crests.football-data.org/397.svg",
  },
  {
    id: 402,
    name: "Brentford FC",
    country: "England",
    crest: "https://crests.football-data.org/402.png",
  },
  {
    id: 563,
    name: "West Ham United FC",
    country: "England",
    crest: "https://crests.football-data.org/563.png",
  },
  {
    id: 770,
    name: "England",
    country: "England",
    crest: "https://crests.football-data.org/770.svg",
  },
  {
    id: 1044,
    name: "AFC Bournemouth",
    country: "England",
    crest: "https://crests.football-data.org/1044.png",
  },
  {
    id: 1072,
    name: "Burton Albion FC",
    country: "England",
    crest: "https://crests.football-data.org/1072.svg",
  },
  {
    id: 1076,
    name: "Coventry City FC",
    country: "England",
    crest: "https://crests.football-data.org/1076.png",
  },
  {
    id: 1077,
    name: "Peterborough United FC",
    country: "England",
    crest: "https://crests.football-data.org/1077.png",
  },
  {
    id: 1081,
    name: "Preston North End FC",
    country: "England",
    crest: "https://crests.football-data.org/1081.png",
  },
  {
    id: 1146,
    name: "Wycombe Wanderers FC",
    country: "England",
    crest: "https://crests.football-data.org/1146.png",
  },
]
